# Main system clock (50 MHz) - DE0-CV CLOCK_50 on PIN_M9
create_clock -name "CLOCK_50" -period 20.000ns [get_ports {CLOCK_50}]

# Automatically constrain PLL and other generated clocks
derive_pll_clocks -create_base_clocks

# 1 MHz UI clock generated by dividing the 100 MHz PLL output by 100
create_generated_clock -name clk1m -source [get_pins {*pll*|outclk*}] -divide_by 100 [get_registers {*clk1m_r*}]

# Automatically calculate clock uncertainty to jitter and other effects.
derive_clock_uncertainty
